server:
  port: 8080
spring:
  application:
    name: server-gateway
  cloud:
    gateway:
      routes:
        - id: film-catalogue-service
          uri: http://localhost:8081/
          predicates:
            - Path=/**
        - id: film-info-service
          uri: http://localhost:8082/
          predicates:
            - Path=/**
        - id: film-notation-service
          uri: http://localhost:8083/
          predicates:
            - Path=/**
          filters:
            - AddRequestHeader=first-request, first-request-header
            - AddResponseHeader=first-response, first-response-header